name: python_flask
description: App Description
ignoreFiles: .git venv
modules:
- name: template
  language: python3.8
  web: flask
  description: Module description
  functions:
  - name: entry
    entry: entry.py
    description: the entry point for the function